#---------------------------
# Home interface for ASKER
#---------------------------
asker_home:
    path: /home
    defaults: { _controller: "INSEADTurkeyBundle:User:home" }
#    type:     annotation