insead_turkey_topic:
    resource: "@INSEADTurkeyBundle/Controller/TopicController.php"
    type:     annotation

insead_turkey_demographic:
    resource: "@INSEADTurkeyBundle/Controller/DemographicController.php"
    type:     annotation

insead_turkey_dictionary:
    resource: "@INSEADTurkeyBundle/Controller/DictionaryController.php"
    type:     annotation

# -------------------------
# Bundle INSEAD Turkey
# -------------------------
insead_turkey:
    resource: "@INSEADTurkeyBundle/Resources/config/routing.yml"
    prefix:   /

# -------------------------
# Bundle INSEAD user
# -------------------------
insead_user:
    resource: "@INSEADUserBundle/Resources/config/routing.yml"
    prefix:   /

