# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        INSEAD\UserBundle\Entity\User: sha512
    role_hierarchy:
            ROLE_ADMIN:       [ROLE_USER, ROLE_ASKER, ROLE_ANSWER]
            ROLE_SUPER_ADMIN: ROLE_ADMIN
            ROLE_ASKER:       ROLE_USER
            ROLE_ASKER_PREMIUM: ROLE_ASKER
            ROLE_ANSWER:       ROLE_USER

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
          id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:      ^/
            anonymous:    true
            provider:     fos_userbundle
            form_login:
              login_path: fos_user_security_login
              check_path: fos_user_security_check
              # Route utilisée après validation du login
              default_target_path: /connected
            logout:
              # Route après logout
              path:       fos_user_security_logout
              target:     /
#            remember_me:
#              secret:     '%secret%'

#    access_control:
#        - { path: ^/?$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/(login|register), role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/, role: ROLE_ADMIN }
