# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #   Surcharge du registration form type de fosuser
    app.form.registration:
        class: INSEAD\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

#Methode helper => helper_services.php
    helper_services:
        class: INSEAD\TurkeyBundle\Services\helper_services
        arguments: ['@doctrine.orm.entity_manager' ,'@service_container', '@security.token_storage']

# pour form question si asker_premium
    insead.turkey.bundle.form.type.question:
        class: INSEAD\TurkeyBundle\Form\QuestionType
        arguments: ["@security.authorization_checker"]
        tags:
            - { name: form.type }

#Ajout filtre twig
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
