# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #   Surcharge du registration form type de fosuser
    app.form.registration:
        class: INSEAD\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

#Methode helper => helper_services.php
    helper_services:
        class: INSEAD\TurkeyBundle\Services\helper_services
        arguments: ['@doctrine.orm.entity_manager' ,'@service_container', '@security.token_storage']

