#---------------------------
#Home interface for ANSWER
#---------------------------
answer_home:
    path: /home
    defaults: { _controller: "INSEADTurkeyBundle:User:home" }
#    type:     annotation